image: docker:latest

services:
  - docker:dind

stages:
  - build
  - deploy

build:
  stage: build
  script:
    - docker build -t wx_tool:$CI_COMMIT_SHORT_SHA .
    - docker tag wx_tool:$CI_COMMIT_SHORT_SHA my-docker-registry/wx_tool:$CI_COMMIT_SHORT_SHA
    - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD my-docker-registry
    - docker push my-docker-registry/wx_tool:$CI_COMMIT_SHORT_SHA

deploy:
  stage: deploy
  image: rancher/cli:v2.3.0
  script:
    - rancher login https://docs.rancher.cn --token w54zhz4j6b89bvp6lq5g5tf2rlbqqwccr8np7l4m2qfbg8s5nwvkrw
    - rancher kubectl create namespace wx_tool
    - rancher kubectl apply -n wx_tool -f deployment.yaml
