image: docker:latest

services:
  - docker:dind

stages:
  - build
  - deploy

build:
  stage: build
  script:
    - docker build -t my-python-app:$CI_COMMIT_SHORT_SHA .
    - docker tag my-python-app:$CI_COMMIT_SHORT_SHA my-docker-registry/my-python-app:$CI_COMMIT_SHORT_SHA
    - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD my-docker-registry
    - docker push my-docker-registry/my-python-app:$CI_COMMIT_SHORT_SHA

deploy:
  stage: deploy
  image: rancher/cli:v2.3.0
  script:
    - rancher login https://my-rancher-server.com/v3 --token $RANCHER_TOKEN
    - rancher kubectl create namespace my-python-app
    - rancher kubectl apply -n my-python-app -f deployment.yaml
